// Credential storage + HTTP Basic Auth for the admin panel.
//
// Two ways to supply credentials:
//   1. Environment variables ADMIN_USER / ADMIN_PASS — set these in your host's
//      dashboard (Render, Railway, Fly.io, etc.). Nothing is written to disk.
//   2. A local admin/.credentials.json file, auto-generated on first run
//      (only a salted hash is stored — never the plaintext password).
// Env vars take priority when both are present.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const CREDS_PATH = path.join(__dirname, '.credentials.json');

function hashPassword(password, salt) {
  return crypto.scryptSync(password, salt, 64).toString('hex');
}

function timingSafeEqualStr(a, b) {
  const bufA = Buffer.from(String(a));
  const bufB = Buffer.from(String(b));
  if (bufA.length !== bufB.length) {
    crypto.timingSafeEqual(bufA, bufA); // keep timing roughly constant
    return false;
  }
  return crypto.timingSafeEqual(bufA, bufB);
}

function loadFileCredentials() {
  if (!fs.existsSync(CREDS_PATH)) return null;
  return JSON.parse(fs.readFileSync(CREDS_PATH, 'utf8'));
}

function generateFileCredentials(username) {
  const password = crypto.randomBytes(12).toString('base64url');
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = hashPassword(password, salt);
  const record = { username: username || 'admin', salt, hash, createdAt: new Date().toISOString() };
  fs.writeFileSync(CREDS_PATH, JSON.stringify(record, null, 2) + '\n');
  return { username: record.username, password };
}

// Ensures credentials exist somewhere. Returns { username, password, source }.
// `password` is the plaintext ONLY when a file-based credential was freshly
// generated by this call — otherwise it's null (never re-exposed).
function ensureCredentials() {
  if (process.env.ADMIN_USER && process.env.ADMIN_PASS) {
    return { username: process.env.ADMIN_USER, password: null, source: 'env' };
  }
  const existing = loadFileCredentials();
  if (existing) return { username: existing.username, password: null, source: 'file' };
  const fresh = generateFileCredentials('admin');
  return { username: fresh.username, password: fresh.password, source: 'file-generated' };
}

function checkCredentials(user, pass) {
  if (process.env.ADMIN_USER && process.env.ADMIN_PASS) {
    return user === process.env.ADMIN_USER && timingSafeEqualStr(pass, process.env.ADMIN_PASS);
  }
  const rec = loadFileCredentials();
  if (!rec) return false;
  if (user !== rec.username) return false;
  return timingSafeEqualStr(hashPassword(pass, rec.salt), rec.hash);
}

// Small in-memory brute-force throttle (per server process).
const attempts = new Map();
const MAX_ATTEMPTS = 8;
const WINDOW_MS = 10 * 60 * 1000;

function isRateLimited(ip) {
  const rec = attempts.get(ip);
  if (!rec) return false;
  if (Date.now() - rec.first > WINDOW_MS) { attempts.delete(ip); return false; }
  return rec.count >= MAX_ATTEMPTS;
}
function recordFailure(ip) {
  const rec = attempts.get(ip);
  if (!rec || Date.now() - rec.first > WINDOW_MS) { attempts.set(ip, { count: 1, first: Date.now() }); return; }
  rec.count++;
}
function recordSuccess(ip) { attempts.delete(ip); }

function requireBasicAuth(req, res) {
  const ip = req.socket.remoteAddress || 'unknown';
  if (isRateLimited(ip)) {
    res.writeHead(429, { 'Content-Type': 'text/plain' });
    res.end('Too many failed login attempts. Try again later.');
    return false;
  }
  const header = req.headers['authorization'] || '';
  const [scheme, encoded] = header.split(' ');
  if (scheme === 'Basic' && encoded) {
    const decoded = Buffer.from(encoded, 'base64').toString('utf8');
    const idx = decoded.indexOf(':');
    const user = idx === -1 ? decoded : decoded.slice(0, idx);
    const pass = idx === -1 ? '' : decoded.slice(idx + 1);
    if (checkCredentials(user, pass)) { recordSuccess(ip); return true; }
    recordFailure(ip);
  }
  res.writeHead(401, { 'WWW-Authenticate': 'Basic realm="Admin"', 'Content-Type': 'text/plain' });
  res.end('Authentication required');
  return false;
}

module.exports = { ensureCredentials, requireBasicAuth, CREDS_PATH };
